# Generated by Django 3.2.4 on 2021-06-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_username",
                    models.CharField(max_length=63, verbose_name="Database username"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabasePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=63, verbose_name="Table name"),
                ),
                (
                    "privilege",
                    models.CharField(
                        choices=[
                            ("I", "INSERT"),
                            ("S", "SELECT"),
                            ("U", "UPDATE"),
                            ("D", "DELETE"),
                            ("T", "TRUNCATE"),
                            ("R", "REFERENCES"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warden.databaseuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("table_name", "privilege", "user")},
            },
        ),
    ]
