name: CI Tests
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: warden
          POSTGRES_DB: warden
          POSTGRES_USER: warden
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.6
            toxenv: "py36-django22"
          - python-version: 3.6
            toxenv: "py36-django3"
          - python-version: 3.7
            toxenv: "py37-django22"
          - python-version: 3.7
            toxenv: "py37-django3"
          - python-version: 3.8
            toxenv: "py38-django22"
          - python-version: 3.8
            toxenv: "py38-django3"
          - python-version: 3.9
            toxenv: "py39-django22"
          - python-version: 3.9
            toxenv: "py39-django3"
          - python-version: 3.9
            toxenv: "linting"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install tox
        run: |
          pip install -U pip
          pip install tox
      - name: Run tests
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
